### ISSUE TITLE
sex

### ISSUE THREAD

**Issue by sasamiil** [hyeonsoft/NWC_Artworks#1]
セックス

**Comment by 2p31-1** [comment]
Sorry, There are none of ways that I can help you

**Comment by 2p31-1** [comment]
1. git for windows를 깐다
2. cmd에서 네가 작업할 폴더로 들어간다 (cd 명령어)
3. `git clone https://github.com/hyeonsoft/NWC_Artworks.git` 을 친다
3 - 1. 뭔 명령어 알려주면서 이름이랑 이메일 치라고 나옴 네 아이디랑 이메일 치셈
3 - 2. 다시 친다
4. 작업한다!
5. 저장한다!
6. `git commit -a` 를 친다 (cmd에서 네가 작업할 폴더에서) -> 이 과정은 일종의 체크 포인트같은거다. 파일 잘못 저장해서 통째로 날아갔다고 치자. 이 때 저장했던 위치로 돌아갈 수 있다.
7. `git push` 를 친다. (처음 치는거면 로그인할 수 있음)
8. github에 네 파일이 업데이트된다. 다음에 작업을 시작하기 전에 `git fetch` 를 쳐서 최신 파일로 동기화해주자.
9. 4~7의 과정 반복
10. PROFIT!!

**Comment by 2p31-1** [comment]
github에 대하여 [이거](https://milooy.wordpress.com/2017/06/21/working-together-with-github-tutorial/) 한번만 읽어봐라
